name: Upload Chinese Font Asset
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'assets/**'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run build script
      run: |
          ./build.ps1
    - name: Create Upload Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: Release/*.7z
        release_name: ${{ env.MY_TAG }}
        tag: ${{ env.MY_TAG }}
        overwrite: true